use [202111040656];
CREATE TABLE T
(
    T# CHAR(4) NOT NULL,
    TNAME CHAR(8) NOT NULL,
    TITLE CHAR(10),
    PRIMARY KEY(T#)
);

CREATE TABLE C
(
    C# CHAR(4) NOT NULL,
    CNAME CHAR (10) NOT NULL,
    T# CHAR(4),
    PRIMARY KEY(C#),
    FOREIGN KEY(T#)REFERENCES T(T#)
);

CREATE TABLE S
(
    S# CHAR(4) NOT NULL,
    SNAME CHAR(8) NOT NULL,
    AGE SMALLINT,
    SEX CHAR(1),
    PRIMARY KEY(S#)
);

CREATE TABLE SC
(
    S# CHAR(4) NOT NULL,
    C# CHAR(4) NOT NULL,
    SCORE SMALLINT,
    PRIMARY KEY(S#,C#),
    FOREIGN KEY(S#)REFERENCES S(S#),
    FOREIGN KEY(C#)REFERENCES C(C#)
);