SELECT S# , SNAME
FROM S
WHERE AGE < 20 AND SEX='F';

SELECT DISTINCT CNAME, C.C#
FROM C, S, SC
WHERE S.S#=SC.S# AND C.C#=SC.C# AND SEX='F';

SELECT T.T# , TNAME
FROM S, SC, T, C
WHERE S.S#=SC.S# AND C.C#=SC.C# AND C.T#=T.T# AND S.SEX='M';

SELECT DISTINCT X.C#
FROM SC AS X, SC AS Y
WHERE X.C#!=Y.C# AND X.S#=Y.S#;

SELECT X.C#
FROM SC AS X , SC AS Y
WHERE X.S#='S1' AND Y.S#='S5' AND X.C#=Y.C#;

SELECT C#
FROM C
WHERE NOT EXISTS(SELECT *
FROM S, SC
WHERE S.S#=SC.S# AND C.C#=SC.C# AND SNAME='TOM'
				 );

SELECT CNAME, C.C#
FROM C
WHERE NOT EXISTS(SELECT *
FROM S
WHERE NOT EXISTS(
				 SELECT *
FROM SC
WHERE S#=S.S# AND C#=C.C#
				                  )
				 );

SELECT DISTINCT S#
FROM SC AS X
WHERE NOT EXISTS(
                 SELECT *
FROM C, T
WHERE C.T#=T.T# AND T.TNAME='ZHOU' AND NOT EXISTS
				 (
				 SELECT *
	FROM SC AS Y
	WHERE X.S#=Y.S# AND X.C#=Y.C#
				 )
                );

SELECT COUNT(DISTINCT C#)
FROM SC;

SELECT AVG(AGE)
FROM S, SC
WHERE SEX='F' AND S.S#=SC.S# AND C#='C1';

SELECT AVG(GRADE)
FROM SC, C, T
WHERE SC.C# IN 
	(SELECT C.C#
FROM C
WHERE T# IN (SELECT T#
FROM T
WHERE TNAME='LIU'
 	  		     )
	);

SELECT C#, COUNT (DISTINCT S#)
FROM SC
GROUP BY(C#)
HAVING COUNT(DISTINCT S#)>5;

SELECT SNAME
FROM S
WHERE S#>ALL(SELECT S#
	FROM S
	WHERE SNAME='ZHAO'
                 )
	AND AGE<ALL(SELECT AGE
	FROM S
	WHERE SNAME='ZHAO'
                 );

SELECT S#, C#
FROM SC
WHERE GRADE>80;

SELECT SNAME, AGE
FROM S
WHERE SNAME LIKE 'Z%';

SELECT SNAME, AGE
FROM S
WHERE SEX='F'AND AGE<ALL(SELECT AVG(AGE)
	FROM S
	WHERE SEX='M'
						     );

ALTER TABLE S ADD CONSTRAINT SEX_S CHECK (SEX='F' OR SEX='M')
INSERT INTO S
VALUES
	('S12', 'SHUI', 23, 'F');

ALTER TABLE S ADD CONSTRAINT AGE_S CHECK (AGE>0 AND AGE <28)
INSERT INTO S
VALUES
	('S13', 'SHUI', 25, 'M');

ALTER TABLE S DROP CONSTRAINT AGE_S;

ALTER TABLE SC ADD CONSTRAINT SC_GRADE CHECK (GRADE BETWEEN 0 AND 120)
INSERT INTO SC
VALUES
	('S11', 'C5', 80);

ALTER TABLE SC DROP CONSTRAINT SC_GRADE
ALTER TABLE SC ADD CONSTRAINT SC_GRADE CHECK (GRADE BETWEEN 0 AND 100)

INSERT INTO SC
VALUES
	('S8', 'C3', 85),
	('S9', 'C2', 87),
	('S10', 'C2', 77);

UPDATE S
   SET AGE=18
   WHERE SNAME='ZHOU';

UPDATE SC
   SET GRADE=0
   WHERE S# IN (SELECT S#
FROM SC, C, T
WHERE SC.C#=C.C# AND C.T#=T.T# AND TNAME='LIU'
			    );

DELETE FROM SC
   WHERE S# IN (SELECT S#
FROM SC
WHERE S#='S10' AND C#='C2'
        		);